spring:
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:shortlinkdb;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_UPPER=false

server:
  servlet:
    context-path: /
  port: 8081

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
